//
// Created by robertvokac on 3/11/25.
//

#ifndef MIGRATIONS_H
#define MIGRATIONS_H
#include <string>


namespace NoteBox::Persistence::Impl::Sqlite {
    constexpr int MIGRATION_COUNT = 14;
    inline std::string migrations[MIGRATION_COUNT] = {

        R"(
CREATE TABLE LITERATURE_SOURCE (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE TEXT NOT NULL,
    AUTHOR TEXT,
    YEAR TEXT,
    PUBLICATION TEXT,
    URL TEXT,
    CONTENT TEXT,

    UNIQUE(TITLE, AUTHOR)
);

        )",

        R"(
CREATE TABLE CONTENT (
    ID TEXT PRIMARY KEY,
    VALUE TEXT
);

        )",


        R"(
CREATE TABLE NOTE (
    ID TEXT PRIMARY KEY,           -- for example '/1a', '/1a2b', etc.
    PARENT_NOTE_ID TEXT,
    TITLE TEXT NOT NULL,
    CONTENT_ID TEXT,
    QUESTION TEXT,
    CREATED_AT INTEGER,
    UPDATED_AT INTEGER,
    LAST_SHOWN_AT INTEGER,
    LAST_REVIEWED_AT INTEGER,
    REVIEW_IN_X_DAYS INTEGER,
    EXPIRES_AT INTEGER,
    IMPORTANCE INTEGER,
    DIFFICULTY INTEGER,
    SOURCE_ID INTEGER,                -- FK for LITERATURE_SOURCE
    FOREIGN KEY(PARENT_NOTE_ID) REFERENCES NOTE(ID),
    FOREIGN KEY(CONTENT_ID) REFERENCES CONTENT(ID),
    FOREIGN KEY(SOURCE_ID) REFERENCES LITERATURE_SOURCE(ID)
);

        )",

        R"(
CREATE TABLE TAG (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL UNIQUE
);



        )",
        R"(
CREATE TABLE NOTE_TAG (
    NOTE_ID TEXT NOT NULL,
    TAG_ID INTEGER NOT NULL,
    PRIMARY KEY(NOTE_ID, TAG_ID),
    FOREIGN KEY(NOTE_ID) REFERENCES NOTE(ID),
    FOREIGN KEY(TAG_ID) REFERENCES TAG(ID)
);


        )",
        R"(
CREATE TABLE REFERENCE (
    FROM_NOTE_ID TEXT NOT NULL,
    TO_NOTE_ID TEXT NOT NULL,
    LINK_TYPE TEXT DEFAULT 'related', -- e.g. 'supports', 'contradicts', etc.
    PRIMARY KEY(FROM_NOTE_ID, TO_NOTE_ID),
    FOREIGN KEY(FROM_NOTE_ID) REFERENCES NOTE(ID),
    FOREIGN KEY(TO_NOTE_ID) REFERENCES NOTE(ID)
);




        )",
            R"(
CREATE TABLE SESSION (
    ID INTEGER PRIMARY KEY CHECK (id = 1), -- always only one row
    CURRENT_PATH TEXT NOT NULL,
    EDITOR_PATH TEXT,
    LAST_OPENED INTEGER                      -- last exiting time
);




        )",
            R"(
CREATE TABLE HISTORY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NOTE_ID TEXT,
    ACTION TEXT,          -- e.g. 'open', 'edit', 'cd'
    TIMESTAMP TEXT,
    FOREIGN KEY(NOTE_ID) REFERENCES NOTE(ID)
);




        )",


        R"(
CREATE TABLE COLLECTION (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    PARENT_COLLECTION_ID INTEGER,
    NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    ORDER_INDEX INTEGER,

    FOREIGN KEY(PARENT_COLLECTION_ID) REFERENCES COLLECTION(ID)
);

        )",

        R"(

CREATE TABLE COLLECTION_NOTE (
    COLLECTION_ID INTEGER NOT NULL,
    NOTE_ID TEXT NOT NULL,
    ORDER_INDEX INTEGER,

    PRIMARY KEY(COLLECTION_ID, NOTE_ID),
    FOREIGN KEY(COLLECTION_ID) REFERENCES COLLECTION(ID),
    FOREIGN KEY(NOTE_ID) REFERENCES NOTE(ID)
);

        )",

        R"(
CREATE TABLE OLD_CONTENT (
    ID TEXT NOT NULL,
    VALUE TEXT NOT NULL,
    ADDED_AT INTEGER NOTE NULL,
    PRIMARY KEY(ID, ADDED_AT),
    FOREIGN KEY(ID) REFERENCES NOTE(ID)
);

        )",

        R"(
CREATE TABLE OLD_ENTITY (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    ENTITY_NAME TEXT NOT NULL,
    ENTITY_ID TEXT NOT NULL,
    VALUE TEXT NOT NULL,
    ADDED_AT INTEGER NOTE NULL
)
        )",
        R"(
CREATE TABLE TERM (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL UNIQUE,
    CATEGORY TEXT,
    NOTE_ID TEXT,
    CONSTRAINT unique_name_category UNIQUE (NAME, CATEGORY),
    FOREIGN KEY(NOTE_ID) REFERENCES NOTE(ID)
);

)",
        R"(
CREATE TABLE IDEA (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TEXT TEXT NOT NULL,
    CATEGORY TEXT DEFAULT 'To be sorted',
    CREATED_AT INTEGER,
    DUE_AT INTEGER
);

        )",

//         R"(
// aaaaaaaa
//         )",



    };
}


#endif //MIGRATIONS_H
