//
// Created by robertvokac on 9/5/25.
//
#pragma once


#define MIND_NET_VERSION_MAYOR 0
#define MIND_NET_VERSION_MINOR 0
#define MIND_NET_VERSION_PATCH 0
#define MIND_NET_VERSION_LABEL snapshot
#define MIND_NET_VERSION MIND_NET_VERSION_MAYOR.MIND_NET_VERSION_MINOR.MIND_NET_VERSION_PATCH-MIND_NET_VERSION_LABEL
#define MIND_NET_BUILD_TIME std::string(__DATE__) + " " + __TIME__

