#Identification
name=Robert Vokac
description=Zettelkasten system for Robert Vokac
environment=Development
#
#host=
#port=
#frontend_port=
database_type=SQLite

#Access
access_mode=PublicFullAccess
registration_mode=Free
default_user_role=Reader

#Secrets
jwt_secret=***
max_log_level=EXPERIMENT
