#Identification
name=Robert Vokac
description=Zettelkasten system for Robert Vokac
environment=Development
dev_mode=false
#
#host=
#port=
#frontend_port=
database_type=SQLite

#Access
access_mode=PublicFullAccess
registration_mode=Free
default_user_role=Reader

#Other
max_log_level=ERROR
allowed_plugins=slip_box, repetition, dictionary
access_token_expires_in=15
refresh_token_expires_in=43200
refresh_token_rotation_threshold_in=10080
